language: php
php:
- '5.6'
- '7.0'
- '7.1'
- '7.2'
matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
cache:
  directories:
  - $HOME/.composer/cache
before_install:
# disable xdebug if available
- phpenv config-rm xdebug.ini || echo "xdebug not available"
# disable default memory limit
- export INI=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
- echo memory_limit = -1 >> $INI

install:
# flags to pass to install
- flags="--ansi --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress"
# update deps to latest in case of high deps build
- if [ "$deps" == "high" ]; then composer config platform.php 7.2.4; composer update $flags; fi
# install dependencies using system provided composer binary
- composer install $flags
# install dependencies using composer from source
# - bin/composer install $flags
